name: Nix Configuration Helper Build

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    name: APK generation
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: nix-config-helper
          path: app/build/outputs/apk/debug/app-debug.apk
